//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaLibro
    {
        public string ISBN { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> AñoEditado { get; set; }
        public Nullable<int> CodigoGenero { get; set; }
        public string Genero { get; set; }
        public string Editorial { get; set; }
        public Nullable<int> CodigoEditorial { get; set; }
    }
}
